name: stack_fin_notes
description: Notes app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 3.26.0
  intl: 0.16.1
  google_fonts: 1.1.2
  scroll_app_bar: 1.0.3
  image_picker: 0.6.7+22
  path_provider:
  just_debounce_it:
  photo_view:
  firebase_auth:
  google_sign_in:
  firebase_core:
  flutter_svg:
  cloud_firestore:
  firebase_storage:
  flutter_staggered_grid_view:
  connectivity:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
